[package]
name = "tokio-tcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
waker-fn = "1.1.0"
mio = { version = "0.8", features = ["net", "os-poll"] }
